steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "deploy/Dockerfile.ui", "-t", "${_UI_IMAGE}", "."]
images:
  - "${_UI_IMAGE}"
substitutions:
  _UI_IMAGE: us-central1-docker.pkg.dev/neurolonicweb/neurolonic-web-app/openswe-ui:latest
