steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "deploy/Dockerfile.harness", "-t", "${_PLATFORM_IMAGE}", "."]
images:
  - "${_PLATFORM_IMAGE}"
substitutions:
  _PLATFORM_IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/alephat/alephat-platform:latest
