apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alephat
resources:
  - namespace.yaml
  - configmap.yaml
  - migration-job.yaml
  - api-deployment.yaml
  - webhook-deployment.yaml
  - harness-deployment.yaml
  - ui-deployment.yaml
  - nats.yaml
  - postgresql.yaml
  - agent-sandbox-networkpolicy.yaml
